config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    devise_for :users
    root "forum_threads#index"
    resources :forum_threads, only: [:show,:new,:create,:edit,:update,:destroy] do
    	resources :forum_posts, only: [:create]
    put :pin, on: :member #on member artinya dia berlaku terhadap satu data
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
    belongs_to :user
    belongs_to :forum_thread, counter_cache: true

    validates :content, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    belongs_to :user
    has_many :forum_posts, dependent: :destroy

    validates :title, presence: true, length: {maximum: 50}
    validates :content, presence: true
    def sticky?
    	sticky_order != 100
    end
    def pin!
    	self.sticky_order = 1
    	self.save
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :forum_threads
  has_many :forum_posts

  enum level: {member: 0,admin: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
	protect_from_forgery with: :exception
	rescue_from Pundit::NotAuthorizedError, with: :pundit_error
	before_action :configure_permitted_parameters, if: :devise_controller?

	private

	def pundit_error
		flash[:notice] = 'Tidak Memiliki Hak Akses'
		redirect_to root_path
	end
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
	before_action :authenticate_user!, only: [:create]
  def create
  	@threads = ForumThread.friendly.find(params[:forum_thread_id])
  	@posts = ForumPost.new(resource_params)

  	@posts.forum_thread = @threads
  	@posts.user = current_user
  	if @posts.save
			puts 'berhasil disimpan'
			redirect_to forum_thread_path(@threads)
		else
			render 'forum_threads/show'
		end
  	
  end

private
  def resource_params
  	params.require(:forum_post).permit(:content)
  end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
	before_action :authenticate_user!, only: [:new,:create] #Untuk memprotect link agar hanya bisa diakses oleh user
	def index
		if params[:search]
			@threads = ForumThread.where('title like ?', "%#{params[:search]}%").paginate(per_page: 5, page: params[:page])
		else
			@threads = ForumThread.order(sticky_order: :asc).order(id: :desc).paginate(per_page: 5, page: params[:page])
		end
	end
	def show
		@threads = ForumThread.friendly.find(params[:id])
		@posts = ForumPost.new
		@post = @threads.forum_posts.paginate(per_page: 3, page: params[:page])
	end
	def new
		@threads = ForumThread.new
	end
	def create
		@threads = ForumThread.new(resource_params)
		@threads.user = current_user

		if @threads.save
			puts 'berhasil disimpan'
			redirect_to root_path
		else
			render 'new'
		end
	end
	def update
		@threads = ForumThread.friendly.find(params[:id])
		authorize @threads

		if @threads.update(resource_params)
			puts 'berhasil diupdate'
			redirect_to forum_thread_path(@threads)
		else
			render 'new'
		end
	end
	def pin
		@threads = ForumThread.friendly.find(params[:id])
		@threads.pin!
		redirect_to root_path
		authorize @threads
	end
	def edit
		@threads = ForumThread.friendly.find(params[:id])
		authorize @threads
	end
	def destroy
		@threads = ForumThread.friendly.find(params[:id])
		authorize @threads

		@threads.destroy
		redirect_to root_path, notice: "Thread Berhasil Dihapus"
	end

	private

	def resource_params
		params.require(:forum_thread).permit(:title, :content)
	end
end

app/helpers/add_index_to_forum_threads_helper.rb
module AddIndexToForumThreadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_post_helper.rb
module ForumPostHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/forum_threads/edit.html.erb
<div class='row'>
	<div class='col-md-6 offset-md-3'>
		<%= render 'layouts/form' %>
	</div>
</div>

app/views/forum_threads/index.html.erb
<div class='row'>
    <div class='col-md-6 offset-md-3'>
        <% if user_signed_in? %>
        <%= link_to "Mari Berdiskusi", new_forum_thread_path, class: 'btn btn-primary' %>
        <% end %>
        <% @threads.each do |t| %>
        <div class='thread'>
            <h4><%= link_to t.title.titleize, forum_thread_path(t) %> 
                <% if t.sticky? %>

                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pin-angle-fill" viewBox="0 0 16 16">
                  <path d="M9.828.722a.5.5 0 0 1 .354.146l4.95 4.95a.5.5 0 0 1 0 .707c-.48.48-1.072.588-1.503.588-.177 0-.335-.018-.46-.039l-3.134 3.134a5.927 5.927 0 0 1 .16 1.013c.046.702-.032 1.687-.72 2.375a.5.5 0 0 1-.707 0l-2.829-2.828-3.182 3.182c-.195.195-1.219.902-1.414.707-.195-.195.512-1.22.707-1.414l3.182-3.182-2.828-2.829a.5.5 0 0 1 0-.707c.688-.688 1.673-.767 2.375-.72a5.922 5.922 0 0 1 1.013.16l3.134-3.133a2.772 2.772 0 0 1-.04-.461c0-.43.108-1.022.589-1.503a.5.5 0 0 1 .353-.146z"/>
              </svg>
              <% end %></h4>

              <div class='meta'>
                <%= I18n.l(t.created_at.to_date) %> oleh <%= t.user.name %>
            </div>

            <div class='content'>
                <%= truncate t.content, length: 150 %>
            </div>
            <% if user_signed_in? %>
            <% if policy(@threads).pin? %>
            <div class='action'>
                <%= link_to 'Pin It', pin_forum_thread_path(t), class: 'btn', method: :put %>
            </div>
            <% end %>
            <% end %>
            <div class='count'>
                <%= t.forum_posts_count %> obrolan
            </div>

            <div style='clear: both'></div>
        </div>
        <% end %>
        <%= will_paginate @threads, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

app/views/forum_threads/new.html.erb
<div class='row'>
	<div class='col-md-6 offset-md-3'>
		<%= render 'layouts/form' %>
	</div>
</div>

app/views/forum_threads/show.html.erb
<div class='row'>
    <div class='col-md-6 offset-md-3'>
        <div class='thread'>
            <h4><%= @threads.title.titleize %></h4>

            <div class='meta'>
                <%= I18n.l(@threads.created_at.to_date) %> oleh <%= @threads.user.name %>
            </div>

            <div class='content'>
                <%= @threads.content %>
            </div>
            <% if user_signed_in? %>
            <% if policy(@threads).edit? %>
            <div class='action-edit'>
                <%= link_to 'Edit', edit_forum_thread_path(@threads), class: 'btn' %>
                <%= link_to 'Delete', forum_thread_path(@threads), method: :delete, data: {confirm: "Apakah Data Ingin Dihapus?"}, class: 'btn' %>
            </div>
            <% end %>
            <% end %>
        </div>
        <% if @threads.forum_posts.any? %>
        <% @post.each do |p| %>
        <div class='thread'>
           <div class='meta'>
            <%= I18n.l(p.created_at.to_date) %> oleh <%= p.user.name %>
        </div>

        <div class='content'>
            <%= p.content %>
        </div>
    </div>
    <div style='clear: both'></div>
    <% end %>
    <% else %>
    <div> Jadilah yang pertama melakukan tanggapan</div>
    <% end %>

    <%= will_paginate @post, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

    <% if @posts.errors.any? %>
    <div class='alert alert-danger alert-dismissible'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <% @posts.errors.full_messages.each do |error| %>
        <span><%= error %></span></br>
        <% end %>
    </div>
    <% end %>
    <% if user_signed_in? %>
    <%= form_for [@threads, @posts] do |f| %>
    <div class="form-group">
        <h5><%= f.label :content %>
            <%= f.text_area :content, rows: 5, class: 'form-control' %></h5>
        </div>
        <div class="form-group">
            <%= f.submit "Buat", class: 'btn btn-primary form-control' %>
        </div>  
        <% end %>
        <% end %>
    </div>
</div>

app/views/layouts/_form.html.erb
<% if @threads.errors.any? %>
<div class='alert alert-danger alert-dismissible'>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<% @threads.errors.full_messages.each do |error| %>
	<span><%= error %></span></br>
	<% end %>
</div>
<% end %>
<%= form_for @threads do |f| %>
<div class="form-group">
	<h5><%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %></h5>
	</div>
	<div class="form-group">
		<h5><%= f.label :content %>
			<%= f.text_area :content, rows: 10, class: 'form-control' %></h5>
		</div>
		<div class="form-group">
			<%= f.submit "Buat", class: 'btn btn-primary form-control' %>
		</div>	
		<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <%= link_to 'Forum', root_path, class: 'navbar-brand' %>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-between" id="bs-example-navbar-collapse-1">
    

      <%= form_tag root_path, method: :get, class: 'form-inline my-2 my-lg-0' do %>
      <div class="form-group">
        <%= text_field_tag :search, nil, class: 'form-control' %>
        <%= submit_tag "Cari", class: 'btn btn-outline-secondary' %>
      </div>
      <% end %>
      <div class="navbar-nav">
        <a href="#" class="nav-item nav-link">Link</a>
        <div class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= user_signed_in? ? current_user.name : 'Halo Guest' %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <div> <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li></div>
            <% else %>
            <li><%= link_to 'Daftar', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrappy</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 
  'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 
  'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>   
  <%= render 'layouts/navbar' %>
  <div class='container'>
    <% flash.each do |key,value| %>
    <div class="aler alert-<%= key %>">
      <%= value %>
    </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>